# Generated by Django 3.1.2 on 2020-11-24 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('genre', models.CharField(choices=[('1', 'Классика'), ('2', 'Фантастика'), ('3', 'Проза')], max_length=15)),
                ('year', models.IntegerField()),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
