# Generated by Django 3.1.2 on 2020-11-24 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('Классика', 'Классика'), ('Фантастика', 'Фантастика'), ('Проза', 'Проза')], max_length=15),
        ),
    ]
